server:
  port: 9000
spring:
  application:
    name: gate-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #          以上是自动从eureka获取服务列表  如果不配置映射规则 可以直接通过服务名访问
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"

            #      routes:
            #        - id : xxxxx
            #          predicates:
            #          - Path=/zzzzz/**
            #          uri : lb://ccccc
            #          filters :
            #          - StripPrefix = 1
            #以上是负载均衡，lb是负载均衡协议（不是http），通过zzzzz 的路径指向ccccc路径的服务 这里不是url   前提是 开启了eureka自动获取列表

#      routes:
#        - id: account-service
#          uri: http://127.0.0.1:8001
#          predicates:
#            - Path=/account/**
#        - id: examination-service
#          uri: http://127.0.0.1:8011
#          predicates:
#            - Path=/examination/**
#        - id: excel-service
#          uri: http://127.0.0.1:8021
#          predicates:
#            - Path=/excel/**
#        - id: file-service
#          uri: http://127.0.0.1:8031
#          predicates:
#            - Path=/file/**
#        - id: mail-service
#          uri: http://127.0.0.1:8041
#          predicates:
#            - Path=/mail/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7900/eureka/