server:
  port: 9121
spring:
  application:
    name: elastic
  datasource:
    username: fzcode
    password: fzcode_9876
    url: jdbc:mysql://192.168.31.150:3306/fzcode?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: false

elastic:
  host: 192.168.31.151
  port: 30200
  scheme : http
  index : testnote