spring:
  cloud:
    config:
      uri: http://192.168.31.154:30201
      profile: prod
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master
  mail:
    host: smtp.126.com
    username: fzcode@126.com
    password: TKOMBJXTWWYJQTMS
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: fzcode@126.com
          to: 757566833@qq.com
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
  instance:
    prefer-ip-address: true
#eureka:
#  client:
#    enabled: false