
spring:
  profiles:
    include: common
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
  instance:
    prefer-ip-address: true
#eureka:
#  client:
#    enabled: false