spring:
  profiles:
    include: common
  cloud:
    config:
      uri: http://127.0.0.1:30201
      profile: dev
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30200/eureka/
  instance:
    prefer-ip-address: true